### ISSUE TITLE
Switching to Markdown

### ISSUE THREAD

**Issue by este-rs** [Ithkuilic-Language-Group/freetnil#6]
I think orgmode is fine, but there are a few issues:

* There’s less support for rendering org files, while Markdown is ubiquitous.
* Markdown doesn’t require you to use zero-width spaces to resolve weird parsing edge cases.
* Markdown is what we already use here—for GitHub Issues.
* GitHub renders org files with the headings off by a level (the main sections of an RFC should be h2’s, not h1’s).
* Orgmode depends on Emacs features for plugin extras and easy editing. Other editors don’t get such Emacsian luxuries (at least not to such an extent). Markdown, on the other hand, is a level playing field.
* GitHub-Flavoured Markdown has table syntax, so that’s not a problem.

May I have everybody’s consent to rewrite the org files into Markdown? Or am I being too ridiculous? cc @porpoiseless.

**Comment by mklcp** [comment]
I agree

**Comment by porpoiseless** [comment]
I have no problem with this.
